title: Strata by HTML5 UP
description: >
  I'm Sanjiv Murthy, a 3rd year student at UC Berkeley majoring in Data Science with a concentration in Business Analytics. I'm interested in software engineering, machine learning, and quant trading. I like to watch Lakers basketball, read, and listen to rap music. 
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "sanjivmurthy"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "sanjivmurthy"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
