title: Sanjiv Murthy 
description: >
  Hi I'm **Sanjiv Murthy**, a 3rd year student at UC Berkeley. Click [here](https://sanjivmurthy.github.io/site/bio/2012/02/10/code-snippets.html) for my bio.
copyright: 2018
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
linkedin_username: "sanjivmurthy"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "sanjivmurthy"
feed_icon: rss
email: "sanjivp98@berkeley.edu"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5



