title: Strata by HTML5 UP
description: >
  I'm **Sanjiv Murthy**, a 3rd year at UC Berkeley. 
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo

linkedin_username: "sanjivmurthy"

github_username:  "sanjivmurthy"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
